MACRO(ADM_audio_plugin  _lib)
        INCLUDE_DIRECTORIES("${CMAKE_BINARY_DIR}/config")
	INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/avidemux/ADM_core/include")
        INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/avidemux/ADM_audiocodec")
if(WIN32)
	TARGET_LINK_LIBRARIES(${_lib} ADM_core)
endif(WIN32)
        INSTALL(TARGETS ${_lib} DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/ADM_plugins/audioDecoder/")
ENDMACRO(ADM_audio_plugin)

