MACRO(checkOpencore)
	IF (NOT OPENCORE_CHECKED)
		OPTION(OPENCORE "" ON)

		MESSAGE(STATUS "Checking for opencore-amr")
		MESSAGE(STATUS "*************************")

		IF (OPENCORE)
			FIND_HEADER_AND_LIB(OPENCORE_AMRNB opencore-amrnb/interf_dec.h opencore-amrnb Decoder_Interface_init)
			PRINT_LIBRARY_INFO("opencore-amrnb" OPENCORE_AMRNB_FOUND "${OPENCORE_AMRNB_INCLUDE_DIR}" "${OPENCORE_AMRNB_LIBRARY_DIR}")
		ELSE (OPENCORE)
			MESSAGE("${MSG_DISABLE_OPTION}")
		ENDIF (OPENCORE)

		SET(ENV{ADM_HAVE_OPENCORE_AMRNB} ${OPENCORE_AMRNB_FOUND})
		SET(OPENCORE_CHECKED 1)

		MESSAGE("")
	ENDIF (NOT OPENCORE_CHECKED)
ENDMACRO(checkOpencore)