MACRO(checkLibxml2)
	MESSAGE(STATUS "Checking for Libxml2")
	MESSAGE(STATUS "********************")

	SET(LibXml2_FIND_QUIETLY TRUE)

	FIND_PACKAGE(LibXml2)
	PRINT_LIBRARY_INFO("Libxml2" LIBXML2_FOUND "${LIBXML2_INCLUDE_DIR} ${LIBXML2_DEFINITIONS}" "${LIBXML2_LIBRARIES}")

	MESSAGE("")
ENDMACRO(checkLibxml2)