# - determine CPU and Operating System
#  ADM_CPU_X86      - x86 CPU architecture was detected
#  ADM_CPU_X86_64   - x86-64 CPU architecture was detected
#  ADM_OS_DARWIN    - Mac OS X was detected
#  ADM_OS_LINUX     - Linux was detected
#  ADM_OS_WINDOWS   - Microsoft Windows was detected

INCLUDE(CMakeDetermineSystem)

# override detected processor for cross-compilation purposes
IF (CROSS_SYSTEM_PROCESSOR)
	SET(CMAKE_SYSTEM_PROCESSOR ${CROSS_SYSTEM_PROCESSOR})
ENDIF (CROSS_SYSTEM_PROCESSOR)

IF (WIN32)
	SET(ADM_OS_WINDOWS 1)
ELSEIF (APPLE AND UNIX)
	SET(ADM_OS_DARWIN 1)
	SET(ADM_BSD_FAMILY 1)
ELSEIF (UNIX)
	SET(ADM_OS_LINUX 1)
	
	IF (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
		SET(ADM_BSD_FAMILY 1)
	ENDIF (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
ENDIF (WIN32)

IF (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i386" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i586" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")
	SET(ADM_CPU_X86 1)
ELSEIF (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "amd64")
	SET(ADM_CPU_X86_64 1)
ELSEIF (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "ppc" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "powerpc" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "Power Macintosh")
	SET(ADM_CPU_PPC 1)
ENDIF (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i386" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i586" OR ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "i686")

IF (NOT ADM_OS_DARWIN AND NOT ADM_OS_WINDOWS AND NOT ADM_OS_LINUX)
	MESSAGE(FATAL_ERROR "Operating System not supported (${CMAKE_SYSTEM_NAME})")
ENDIF (NOT ADM_OS_DARWIN AND NOT ADM_OS_WINDOWS AND NOT ADM_OS_LINUX)

IF (NOT ADM_CPU_X86 AND NOT ADM_CPU_X86_64)
	MESSAGE(FATAL_ERROR "CPU not supported (${CMAKE_SYSTEM_PROCESSOR})")
ENDIF (NOT ADM_CPU_X86 AND NOT ADM_CPU_X86_64)	