MACRO(INIT_AUDIO_DEVICE _lib)
	INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/../avidemux/ADM_core/include")
	INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/../avidemux/ADM_audiodevice/")
ENDMACRO(INIT_AUDIO_DEVICE)

MACRO(INSTALL_AUDIODEVICE _lib)
	INSTALL(TARGETS ${_lib} DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/ADM_plugins/audioDevices/")
ENDMACRO(INSTALL_AUDIODEVICE)
