# Small Macro to check head & lib and set output variable
# all in one line, cmake is cool :)
MACRO (ADM_CHECK_HL _banner _includeName _libName _libFunc _varToSet)
MESSAGE(STATUS "<Checking for ${_banner}>")
MESSAGE(STATUS "<******************************>")
#set(${_varToSet} FALSE)
CHECK_INCLUDE_FILES("${_includeName}" ${_varToSet}_H)
#MESSAGE("OUT ${HAVE_IT_H}")
if(${_varToSet}_H)
  MESSAGE(STATUS "Header ${_includeName} Found")
#FIND_LIBRARY(ADM_PATH_LIB ${_libName})
  CHECK_LIBRARY_EXISTS(${_libName} ${_libFunc} "" ${_varToSet}_L)
  if(${_varToSet}_L)
        MESSAGE(STATUS "Lib ${_libName} Found")
        SET(${_varToSet}  1)
  else(${_varToSet}_L)
        MESSAGE("Lib not found")
  endif(${_varToSet}_L)
else(${_varToSet}_H)
  MESSAGE("Header not found(${_includeName})")
endif(${_varToSet}_H)

if(${_varToSet})
   MESSAGE(STATUS "${_banner} OK")
else(${_varToSet})
     MESSAGE(STATUS "${_banner} support off")
endif(${_varToSet})

ENDMACRO (ADM_CHECK_HL _includeName _libName _libFunc _varToSet)


