MACRO(ADM_DISPLAY _name _val)
#MESSAGE("${_val}")
if(${_val} EQUAL 1)
  set(s "Yes")
else(${_val} EQUAL 1)
  set(s "No")
endif(${_val} EQUAL 1)
MESSAGE("${_name}  ${s}") 
ENDMACRO(ADM_DISPLAY _name _val)



MESSAGE("*******************")
MESSAGE("**  Summary      **")
MESSAGE("*******************")
MESSAGE("Gtk,${GTK_FOUND}")
MESSAGE("Qt4,${QT4_FOUND}")
MESSAGE("*** Video Codec ***")
ADM_DISPLAY("X264      " USE_X264)
ADM_DISPLAY("Xvid4     " USE_XVID_4)
MESSAGE("*** Audio Codec ***")
ADM_DISPLAY("LAME      " HAVE_LIBMP3LAME)
ADM_DISPLAY("FAAD      " USE_FAAD)
ADM_DISPLAY("FAAC      " USE_FAAC)
ADM_DISPLAY("Vorbis    " USE_VORBIS)
MESSAGE("*** Misc       ***")
ADM_DISPLAY("FreeType  " USE_FREETYPE)
ADM_DISPLAY("FontConfig" USE_FONTCONFIG)
MESSAGE("*******************")
MESSAGE("*******************")
