# Find arts CFLAGS etc

MESSAGE(STATUS "<** ARTS **>")
MESSAGE(STATUS "<---------->")
FIND_PROGRAM(ARTS_CONFIG_EXECUTABLE artsc-config)
MARK_AS_ADVANCED(ARTS_CONFIG_EXECUTABLE)

IF(ARTS_CONFIG_EXECUTABLE)
    EXECUTE_PROCESS(COMMAND ${ARTS_CONFIG_EXECUTABLE} --cflags
      OUTPUT_VARIABLE ARTS_CFLAGS
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    MESSAGE(STATUS "Arts cflags : ${ARTS_CFLAGS}")
    EXECUTE_PROCESS(COMMAND ${ARTS_CONFIG_EXECUTABLE} --libs
      OUTPUT_VARIABLE ARTS_LDFLAGS
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    MESSAGE(STATUS "Arts ldflags : ${ARTS_LDFLAGS}")
    SET(USE_ARTS 1)
ELSE(ARTS_CONFIG_EXECUTABLE)
MESSAGE(STATUS "Not found")
ENDIF(ARTS_CONFIG_EXECUTABLE)


# FindSubversion.cmake ends here.
