MESSAGE(STATUS "CMAKE_INSTALL_PREFIX        : ${CMAKE_INSTALL_PREFIX}")

IF (WIN32)
	SET(avidemux_bin_path ${CMAKE_INSTALL_PREFIX})
	SET(avidemux_lib_path ${CMAKE_INSTALL_PREFIX})
	set(avidemux_include_path ${CMAKE_INSTALL_PREFIX}/include)
	set(ADM_PLUGIN_DIR plugins)
ELSE (WIN32)
	IF (CMAKE_C_IMPLICIT_LINK_DIRECTORIES MATCHES "\\/lib64([; ]|$)")
		SET(relative_lib_dir lib64)
	ELSEIF (CMAKE_C_IMPLICIT_LINK_DIRECTORIES MATCHES "\\/lib32([; ]|$)")
		SET(relative_lib_dir lib32)
	ELSE (CMAKE_C_IMPLICIT_LINK_DIRECTORIES MATCHES "\\/lib64([; ]|$)")
		SET(relative_lib_dir lib)
	ENDIF (CMAKE_C_IMPLICIT_LINK_DIRECTORIES MATCHES "\\/lib64([; ]|$)")

	SET(avidemux_bin_path ${CMAKE_INSTALL_PREFIX}/bin)
	SET(avidemux_lib_path ${CMAKE_INSTALL_PREFIX}/${relative_lib_dir})
	set(avidemux_include_path ${CMAKE_INSTALL_PREFIX}/include/avidemux/${ADM_MAIN_VERSION})
	set(ADM_PLUGIN_DIR ADM_plugins6)
ENDIF(WIN32)

if (NOT FAKEROOT)
	SET(avidemux_fakeroot "")
else (NOT FAKEROOT)
	SET(avidemux_fakeroot "${FAKEROOT}/")
endif (NOT FAKEROOT)

set(pluginLibraryPath "${avidemux_lib_path}/${ADM_PLUGIN_DIR}")
SET(AVIDEMUX_SEARCH_INCLUDE_PATH ${avidemux_fakeroot}${avidemux_include_path})
SET(AVIDEMUX_SEARCH_LIB_PATH     ${avidemux_fakeroot}${avidemux_lib_path})
SET(AVIDEMUX_RELATIVE_LIB_DIR ${relative_lib_dir})

if (NOT ADM_FFMPEG_INCLUDE_PATH)
	set(ADM_FFMPEG_INCLUDE_PATH "${AVIDEMUX_SEARCH_INCLUDE_PATH}/ffmpeg")
endif (NOT ADM_FFMPEG_INCLUDE_PATH)

if (NOT ADM_FFMPEG_LIBRARY_PATH)
	set(ADM_FFMPEG_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}")
endif (NOT ADM_FFMPEG_LIBRARY_PATH)

if (NOT ADM_CORE_INCLUDE_PATH)
	set(ADM_CORE_INCLUDE_PATH "${AVIDEMUX_SEARCH_INCLUDE_PATH}/core")
endif (NOT ADM_CORE_INCLUDE_PATH)

if (NOT ADM_CORE_LIBRARY_PATH)
	set(ADM_CORE_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}")
endif (NOT ADM_CORE_LIBRARY_PATH)

if (NOT ADM_CLI_INCLUDE_PATH)
	set(ADM_CLI_INCLUDE_PATH "${AVIDEMUX_SEARCH_INCLUDE_PATH}/cli")
endif (NOT ADM_CLI_INCLUDE_PATH)

if (NOT ADM_CLI_LIBRARY_PATH)
	set(ADM_CLI_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}")
endif (NOT ADM_CLI_LIBRARY_PATH)

if (NOT ADM_GTK_INCLUDE_PATH)
	set(ADM_GTK_INCLUDE_PATH "${AVIDEMUX_SEARCH_INCLUDE_PATH}/gtk")
endif (NOT ADM_GTK_INCLUDE_PATH)

if (NOT ADM_GTK_LIBRARY_PATH)
	set(ADM_GTK_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}")
endif (NOT ADM_GTK_LIBRARY_PATH)

if (NOT ADM_GLADE_LIBRARY_PATH)
	set(ADM_GLADE_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}/ADM_glade")
endif (NOT ADM_GLADE_LIBRARY_PATH)

if (NOT ADM_QT_INCLUDE_PATH)
	set(ADM_QT_INCLUDE_PATH "${AVIDEMUX_SEARCH_INCLUDE_PATH}/qt")
endif (NOT ADM_QT_INCLUDE_PATH)

if (NOT ADM_QT_LIBRARY_PATH)
	set(ADM_QT_LIBRARY_PATH "${AVIDEMUX_SEARCH_LIB_PATH}")
endif (NOT ADM_QT_LIBRARY_PATH)

MESSAGE(STATUS "FAKEROOT                    : ${avidemux_fakeroot}")
MESSAGE(STATUS "AVIDEMUX_BIN_PATH           : ${avidemux_bin_path}")
MESSAGE(STATUS "AVIDEMUX_LIB_PATH           : ${avidemux_lib_path}")
MESSAGE(STATUS "AVIDEMUX_INCLUDE_PATH       : ${avidemux_include_path}")
MESSAGE(STATUS "AVIDEMUX_SEARCH_INCLUDE_PATH: ${AVIDEMUX_SEARCH_INCLUDE_PATH}")
MESSAGE(STATUS "AVIDEMUX_SEARCH_LIB_PATH    : ${AVIDEMUX_SEARCH_LIB_PATH}")

#
# MACRO TO INSTALL REGULAR LIBS
#
MACRO (ADM_INSTALL_LIB lib)
	INSTALL(TARGETS ${lib} RUNTIME DESTINATION ${avidemux_bin_path}  LIBRARY DESTINATION ${avidemux_lib_path}  ARCHIVE DESTINATION ${avidemux_lib_path})

	if (MSVC)
		ADD_DEPENDENCIES(install_after_all ${lib})
	endif (MSVC)
ENDMACRO (ADM_INSTALL_LIB)

MACRO (ADM_INSTALL_LIB_FILES files)
	INSTALL(FILES ${files} DESTINATION ${avidemux_lib_path})
ENDMACRO (ADM_INSTALL_LIB_FILES)

MACRO (ADM_INSTALL_GLADE_LIB_FILES subDirectory)
	INSTALL(FILES ${ARGN} DESTINATION ${avidemux_lib_path}/ADM_glade/${subDirectory})
ENDMACRO (ADM_INSTALL_GLADE_LIB_FILES)

MACRO (ADM_INSTALL_PLUGIN_LIB subDirectory lib)
	install(TARGETS ${lib} DESTINATION ${pluginLibraryPath}/${subDirectory})

	if (MSVC)
		ADD_DEPENDENCIES(install_after_all ${lib})
	endif (MSVC)
ENDMACRO (ADM_INSTALL_PLUGIN_LIB)

MACRO (ADM_INSTALL_PLUGIN_FILES subDirectory)
	install(FILES ${ARGN} DESTINATION ${pluginLibraryPath}/${subDirectory})
ENDMACRO (ADM_INSTALL_PLUGIN_FILES)

#
# MACRO TO INSTALL REGULAR BIN
#
MACRO (ADM_INSTALL_BIN lib)
	INSTALL(TARGETS ${lib} RUNTIME DESTINATION ${avidemux_bin_path}  LIBRARY DESTINATION ${avidemux_lib_path}  ARCHIVE DESTINATION ${avidemux_lib_path})

	if (MSVC)
		ADD_DEPENDENCIES(install_after_all ${lib})
	endif (MSVC)
ENDMACRO (ADM_INSTALL_BIN)

MACRO (ADM_INSTALL_FFMPEG_HEADER_FILES library)
	install(FILES ${ARGN} DESTINATION ${avidemux_include_path}/ffmpeg/${library})
ENDMACRO (ADM_INSTALL_FFMPEG_HEADER_FILES)

MACRO (ADM_INSTALL_CORE_HEADER_FILES)
	install(FILES ${ARGN} DESTINATION ${avidemux_include_path}/core)
ENDMACRO (ADM_INSTALL_CORE_HEADER_FILES)

MACRO (ADM_INSTALL_CLI_HEADER_FILES)
	install(FILES ${ARGN} DESTINATION ${avidemux_include_path}/cli)
ENDMACRO (ADM_INSTALL_CLI_HEADER_FILES)

MACRO (ADM_INSTALL_GTK_HEADER_FILES)
	install(FILES ${ARGN} DESTINATION ${avidemux_include_path}/gtk)
ENDMACRO (ADM_INSTALL_GTK_HEADER_FILES)

MACRO (ADM_INSTALL_QT_HEADER_FILES)
	install(FILES ${ARGN} DESTINATION ${avidemux_include_path}/qt)
ENDMACRO (ADM_INSTALL_QT_HEADER_FILES)