/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GdkPixbuf *mainWindow_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menuBar;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *open_video1;
  GtkWidget *image2035;
  GtkWidget *run_script1;
  GtkWidget *image2036;
  GtkWidget *append_video1;
  GtkWidget *image2037;
  GtkWidget *separator1;
  GtkWidget *save_stuff;
  GtkWidget *save_stuff_menu;
  GtkWidget *save_as_avi1;
  GtkWidget *save_images1;
  GtkWidget *save_images1_menu;
  GtkWidget *save_image1;
  GtkWidget *save_jpg_image1;
  GtkWidget *save_selection_as_jpegs1;
  GtkWidget *requantize_mpeg1;
  GtkWidget *project1;
  GtkWidget *project1_menu;
  GtkWidget *load_project;
  GtkWidget *image2038;
  GtkWidget *save_project_as1;
  GtkWidget *image2039;
  GtkWidget *save_current_project;
  GtkWidget *image2040;
  GtkWidget *avi_muxer_options1;
  GtkWidget *video_informations1;
  GtkWidget *image2041;
  GtkWidget *quit1;
  GtkWidget *image2042;
  GtkWidget *play_1;
  GtkWidget *play_1_menu;
  GtkWidget *play_video1;
  GtkWidget *decoder_options1;
  GtkWidget *set_postprocessing1;
  GtkWidget *separator9;
  GtkWidget *next_frame1;
  GtkWidget *image2043;
  GtkWidget *previous_frame1;
  GtkWidget *image2044;
  GtkWidget *next_intra_frame1;
  GtkWidget *image2045;
  GtkWidget *previous_intra_frame1;
  GtkWidget *image2046;
  GtkWidget *search_next_black_frame1;
  GtkWidget *search_previous_black_frame1;
  GtkWidget *jum_to_frame1;
  GtkWidget *image2047;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *cut1;
  GtkWidget *image2048;
  GtkWidget *copy1;
  GtkWidget *image2049;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *image2050;
  GtkWidget *separator5;
  GtkWidget *set_marker_a1;
  GtkWidget *set_marker_b1;
  GtkWidget *separator4;
  GtkWidget *go_to_marker_a1;
  GtkWidget *go_to_marker_b1;
  GtkWidget *separator10;
  GtkWidget *reset_edits1;
  GtkWidget *image2051;
  GtkWidget *audio_source1;
  GtkWidget *audio_source1_menu;
  GtkWidget *source1;
  GtkWidget *source1_menu;
  GtkWidget *current_video1;
  GtkWidget *external_mpeg;
  GtkWidget *external_wav1;
  GtkWidget *external_ac1;
  GtkWidget *none1;
  GtkWidget *separator12;
  GtkWidget *build_vbr_time_map1;
  GtkWidget *second_audio_track1;
  GtkWidget *second_audio_track1_menu;
  GtkWidget *mp3_file1;
  GtkWidget *ac3_file1;
  GtkWidget *pipe_audio_to1;
  GtkWidget *pipe_audio_to1_menu;
  GtkWidget *to_toolame1;
  GtkWidget *to_lame1;
  GtkWidget *to_other1;
  GtkWidget *save_audio1;
  GtkWidget *misc1;
  GtkWidget *misc1_menu;
  GtkWidget *preferences1;
  GtkWidget *separator13;
  GtkWidget *check_frames;
  GtkWidget *bitrate_histogram1;
  GtkWidget *rebuild_frames;
  GtkWidget *separator14;
  GtkWidget *ocr_vobsub_2_srt;
  GtkWidget *separator15;
  GtkWidget *change_fps;
  GtkWidget *videoencoder;
  GtkWidget *audio_encoder1;
  GtkWidget *about1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar1;
  GtkWidget *buttonOpen;
  GtkWidget *buttonSaveAvi;
  GtkWidget *buttonRecent;
  GtkWidget *alignment10;
  GtkWidget *hbox13;
  GtkWidget *image633;
  GtkWidget *label14;
  GtkWidget *buttonInfo;
  GtkWidget *alignment11;
  GtkWidget *hbox15;
  GtkWidget *image634;
  GtkWidget *label15;
  GtkWidget *togglebuttonPreview;
  GtkWidget *toggleOutput;
  GtkWidget *hbox14;
  GtkWidget *handlebox1;
  GtkWidget *vbox5;
  GtkWidget *vbox6;
  GtkWidget *frame2;
  GtkWidget *vbox7;
  GtkWidget *optionVCodec;
  GtkWidget *buttonConfV;
  GtkWidget *buttonBitrate;
  GtkWidget *buttonFilters;
  GtkWidget *togglebuttonVideo;
  GtkWidget *Video;
  GtkWidget *frame3;
  GtkWidget *vbox8;
  GtkWidget *optionACodec;
  GtkWidget *buttonConfA;
  GtkWidget *buttonAudioFilter;
  GtkWidget *togglebuttonAudio;
  GtkWidget *Audio;
  GtkWidget *frame4;
  GtkWidget *optionmenu1;
  GtkWidget *menu1;
  GtkWidget *avi1;
  GtkWidget *ogm1;
  GtkWidget *mpeg_video_only1;
  GtkWidget *mpeg_ps1;
  GtkWidget *mpeg_ts1;
  GtkWidget *avi_dual_audio1;
  GtkWidget *avi_unpacked_vop1;
  GtkWidget *label17;
  GtkWidget *guiDrawing;
  GtkWidget *sliderNavigate;
  GtkWidget *hbox17;
  GtkWidget *vbox3;
  GtkWidget *handlebox3;
  GtkWidget *hbox10;
  GtkWidget *buttonPlay;
  GtkWidget *image591;
  GtkWidget *buttonStop;
  GtkWidget *image592;
  GtkWidget *buttonPrevFrame;
  GtkWidget *image593;
  GtkWidget *buttonNextFrame;
  GtkWidget *image594;
  GtkWidget *buttonPrevKFrame;
  GtkWidget *image595;
  GtkWidget *buttonNextKFrame;
  GtkWidget *image596;
  GtkWidget *buttonMarkA;
  GtkWidget *image597;
  GtkWidget *buttonMarkB;
  GtkWidget *image598;
  GtkWidget *buttonBegin;
  GtkWidget *image599;
  GtkWidget *buttonEnd;
  GtkWidget *image600;
  GtkWidget *buttonPrevBlack;
  GtkWidget *image601;
  GtkWidget *buttonNextBlack;
  GtkWidget *image602;
  GtkWidget *hbox16;
  GtkWidget *label1;
  GtkWidget *boxCurFrame;
  GtkWidget *labelTotalFrame;
  GtkWidget *label4;
  GtkWidget *boxCurTime;
  GtkWidget *labelTotalTime;
  GtkWidget *labelFrameType;
  GtkWidget *frame1;
  GtkWidget *vbox4;
  GtkWidget *table1;
  GtkWidget *labelMarkA;
  GtkWidget *labelMarkB;
  GtkWidget *buttonGotoA;
  GtkWidget *buttonGotoB;
  GtkWidget *label16;
  extern GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainWindow, "mainWindow");
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("Avidemux2"));
  mainWindow_icon_pixbuf = create_pixbuf ("about.xpm");
  if (mainWindow_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (mainWindow), mainWindow_icon_pixbuf);
      gdk_pixbuf_unref (mainWindow_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  menuBar = gtk_menu_bar_new ();
  gtk_widget_set_name (menuBar, "menuBar");
  gtk_widget_show (menuBar);
  gtk_box_pack_start (GTK_BOX (vbox1), menuBar, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (menuBar, GTK_CAN_FOCUS);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menuBar), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem1_menu, "menuitem1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  open_video1 = gtk_image_menu_item_new_with_mnemonic (_("_Open Video..."));
  gtk_widget_set_name (open_video1, "open_video1");
  gtk_widget_show (open_video1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open_video1);
  gtk_widget_add_accelerator (open_video1, "activate", accel_group,
                              GDK_O, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2035 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2035, "image2035");
  gtk_widget_show (image2035);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open_video1), image2035);

  run_script1 = gtk_image_menu_item_new_with_mnemonic (_("_Run Script..."));
  gtk_widget_set_name (run_script1, "run_script1");
  gtk_widget_show (run_script1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), run_script1);

  image2036 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2036, "image2036");
  gtk_widget_show (image2036);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (run_script1), image2036);

  append_video1 = gtk_image_menu_item_new_with_mnemonic (_("_Append Video..."));
  gtk_widget_set_name (append_video1, "append_video1");
  gtk_widget_show (append_video1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), append_video1);
  gtk_widget_add_accelerator (append_video1, "activate", accel_group,
                              GDK_A, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2037 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2037, "image2037");
  gtk_widget_show (image2037);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (append_video1), image2037);

  separator1 = gtk_menu_item_new ();
  gtk_widget_set_name (separator1, "separator1");
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  save_stuff = gtk_menu_item_new_with_mnemonic (_("_Save"));
  gtk_widget_set_name (save_stuff, "save_stuff");
  gtk_widget_show (save_stuff);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_stuff);

  save_stuff_menu = gtk_menu_new ();
  gtk_widget_set_name (save_stuff_menu, "save_stuff_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (save_stuff), save_stuff_menu);

  save_as_avi1 = gtk_menu_item_new_with_mnemonic (_("Save _Video..."));
  gtk_widget_set_name (save_as_avi1, "save_as_avi1");
  gtk_widget_show (save_as_avi1);
  gtk_container_add (GTK_CONTAINER (save_stuff_menu), save_as_avi1);
  gtk_widget_add_accelerator (save_as_avi1, "activate", accel_group,
                              GDK_S, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  save_images1 = gtk_menu_item_new_with_mnemonic (_("Save _Images"));
  gtk_widget_set_name (save_images1, "save_images1");
  gtk_widget_show (save_images1);
  gtk_container_add (GTK_CONTAINER (save_stuff_menu), save_images1);

  save_images1_menu = gtk_menu_new ();
  gtk_widget_set_name (save_images1_menu, "save_images1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (save_images1), save_images1_menu);

  save_image1 = gtk_menu_item_new_with_mnemonic (_("Save _BMP Image..."));
  gtk_widget_set_name (save_image1, "save_image1");
  gtk_widget_show (save_image1);
  gtk_container_add (GTK_CONTAINER (save_images1_menu), save_image1);
  gtk_widget_add_accelerator (save_image1, "activate", accel_group,
                              GDK_M, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  save_jpg_image1 = gtk_menu_item_new_with_mnemonic (_("Save _JPEG Image..."));
  gtk_widget_set_name (save_jpg_image1, "save_jpg_image1");
  gtk_widget_show (save_jpg_image1);
  gtk_container_add (GTK_CONTAINER (save_images1_menu), save_jpg_image1);
  gtk_widget_add_accelerator (save_jpg_image1, "activate", accel_group,
                              GDK_J, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  save_selection_as_jpegs1 = gtk_menu_item_new_with_mnemonic (_("Save _Selection as JPEGs..."));
  gtk_widget_set_name (save_selection_as_jpegs1, "save_selection_as_jpegs1");
  gtk_widget_show (save_selection_as_jpegs1);
  gtk_container_add (GTK_CONTAINER (save_images1_menu), save_selection_as_jpegs1);

  requantize_mpeg1 = gtk_menu_item_new_with_mnemonic (_("Requantize _MPEG..."));
  gtk_widget_set_name (requantize_mpeg1, "requantize_mpeg1");
  gtk_widget_show (requantize_mpeg1);
  gtk_container_add (GTK_CONTAINER (save_stuff_menu), requantize_mpeg1);
  gtk_widget_add_accelerator (requantize_mpeg1, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  project1 = gtk_menu_item_new_with_mnemonic (_("_Project"));
  gtk_widget_set_name (project1, "project1");
  gtk_widget_show (project1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), project1);

  project1_menu = gtk_menu_new ();
  gtk_widget_set_name (project1_menu, "project1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (project1), project1_menu);

  load_project = gtk_image_menu_item_new_with_mnemonic (_("_Load Project..."));
  gtk_widget_set_name (load_project, "load_project");
  gtk_widget_show (load_project);
  gtk_container_add (GTK_CONTAINER (project1_menu), load_project);
  gtk_widget_add_accelerator (load_project, "activate", accel_group,
                              GDK_O, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  image2038 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2038, "image2038");
  gtk_widget_show (image2038);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (load_project), image2038);

  save_project_as1 = gtk_image_menu_item_new_with_mnemonic (_("Save Project _as ..."));
  gtk_widget_set_name (save_project_as1, "save_project_as1");
  gtk_widget_show (save_project_as1);
  gtk_container_add (GTK_CONTAINER (project1_menu), save_project_as1);

  image2039 = gtk_image_new_from_stock ("gtk-save-as", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2039, "image2039");
  gtk_widget_show (image2039);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save_project_as1), image2039);

  save_current_project = gtk_image_menu_item_new_with_mnemonic (_("_Save Project"));
  gtk_widget_set_name (save_current_project, "save_current_project");
  gtk_widget_show (save_current_project);
  gtk_container_add (GTK_CONTAINER (project1_menu), save_current_project);
  gtk_widget_add_accelerator (save_current_project, "activate", accel_group,
                              GDK_S, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  image2040 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2040, "image2040");
  gtk_widget_show (image2040);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save_current_project), image2040);

  avi_muxer_options1 = gtk_menu_item_new_with_mnemonic (_("AVI _Muxer Options"));
  gtk_widget_set_name (avi_muxer_options1, "avi_muxer_options1");
  gtk_widget_show (avi_muxer_options1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), avi_muxer_options1);
  gtk_widget_add_accelerator (avi_muxer_options1, "activate", accel_group,
                              GDK_U, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  video_informations1 = gtk_image_menu_item_new_with_mnemonic (_("Video _Information"));
  gtk_widget_set_name (video_informations1, "video_informations1");
  gtk_widget_show (video_informations1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), video_informations1);
  gtk_widget_add_accelerator (video_informations1, "activate", accel_group,
                              GDK_I, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2041 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2041, "image2041");
  gtk_widget_show (image2041);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (video_informations1), image2041);

  quit1 = gtk_image_menu_item_new_with_mnemonic (_("_Quit"));
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  image2042 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2042, "image2042");
  gtk_widget_show (image2042);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit1), image2042);

  play_1 = gtk_menu_item_new_with_mnemonic (_("_Play "));
  gtk_widget_set_name (play_1, "play_1");
  gtk_widget_show (play_1);
  gtk_container_add (GTK_CONTAINER (menuBar), play_1);

  play_1_menu = gtk_menu_new ();
  gtk_widget_set_name (play_1_menu, "play_1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (play_1), play_1_menu);

  play_video1 = gtk_menu_item_new_with_mnemonic (_("Play _Video"));
  gtk_widget_set_name (play_video1, "play_video1");
  gtk_widget_show (play_video1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), play_video1);
  gtk_widget_add_accelerator (play_video1, "activate", accel_group,
                              GDK_P, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  decoder_options1 = gtk_menu_item_new_with_mnemonic (_("_Decoder Options"));
  gtk_widget_set_name (decoder_options1, "decoder_options1");
  gtk_widget_show (decoder_options1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), decoder_options1);
  gtk_widget_add_accelerator (decoder_options1, "activate", accel_group,
                              GDK_P, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  set_postprocessing1 = gtk_menu_item_new_with_mnemonic (_("_Set Postprocessing..."));
  gtk_widget_set_name (set_postprocessing1, "set_postprocessing1");
  gtk_widget_show (set_postprocessing1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), set_postprocessing1);
  gtk_tooltips_set_tip (tooltips, set_postprocessing1, _("Select postprocessing level"), NULL);
  gtk_widget_add_accelerator (set_postprocessing1, "activate", accel_group,
                              GDK_T, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator9 = gtk_menu_item_new ();
  gtk_widget_set_name (separator9, "separator9");
  gtk_widget_show (separator9);
  gtk_container_add (GTK_CONTAINER (play_1_menu), separator9);
  gtk_widget_set_sensitive (separator9, FALSE);

  next_frame1 = gtk_image_menu_item_new_with_mnemonic (_("_Next Frame"));
  gtk_widget_set_name (next_frame1, "next_frame1");
  gtk_widget_show (next_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), next_frame1);
  gtk_widget_add_accelerator (next_frame1, "activate", accel_group,
                              GDK_6, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2043 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2043, "image2043");
  gtk_widget_show (image2043);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (next_frame1), image2043);

  previous_frame1 = gtk_image_menu_item_new_with_mnemonic (_("_Previous Frame"));
  gtk_widget_set_name (previous_frame1, "previous_frame1");
  gtk_widget_show (previous_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), previous_frame1);
  gtk_widget_add_accelerator (previous_frame1, "activate", accel_group,
                              GDK_4, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2044 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2044, "image2044");
  gtk_widget_show (image2044);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (previous_frame1), image2044);

  next_intra_frame1 = gtk_image_menu_item_new_with_mnemonic (_("N_ext Intra Frame"));
  gtk_widget_set_name (next_intra_frame1, "next_intra_frame1");
  gtk_widget_show (next_intra_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), next_intra_frame1);
  gtk_widget_add_accelerator (next_intra_frame1, "activate", accel_group,
                              GDK_8, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2045 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2045, "image2045");
  gtk_widget_show (image2045);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (next_intra_frame1), image2045);

  previous_intra_frame1 = gtk_image_menu_item_new_with_mnemonic (_("P_revious Intra Frame"));
  gtk_widget_set_name (previous_intra_frame1, "previous_intra_frame1");
  gtk_widget_show (previous_intra_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), previous_intra_frame1);
  gtk_widget_add_accelerator (previous_intra_frame1, "activate", accel_group,
                              GDK_2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2046 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2046, "image2046");
  gtk_widget_show (image2046);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (previous_intra_frame1), image2046);

  search_next_black_frame1 = gtk_menu_item_new_with_mnemonic (_("Search Next _Black Frame"));
  gtk_widget_set_name (search_next_black_frame1, "search_next_black_frame1");
  gtk_widget_show (search_next_black_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), search_next_black_frame1);

  search_previous_black_frame1 = gtk_menu_item_new_with_mnemonic (_("Search Previous Black _Frame"));
  gtk_widget_set_name (search_previous_black_frame1, "search_previous_black_frame1");
  gtk_widget_show (search_previous_black_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), search_previous_black_frame1);

  jum_to_frame1 = gtk_image_menu_item_new_with_mnemonic (_("_Jump to Frame..."));
  gtk_widget_set_name (jum_to_frame1, "jum_to_frame1");
  gtk_widget_show (jum_to_frame1);
  gtk_container_add (GTK_CONTAINER (play_1_menu), jum_to_frame1);
  gtk_widget_add_accelerator (jum_to_frame1, "activate", accel_group,
                              GDK_G, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2047 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2047, "image2047");
  gtk_widget_show (image2047);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (jum_to_frame1), image2047);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_set_name (menuitem2, "menuitem2");
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menuBar), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_widget_set_name (menuitem2_menu, "menuitem2_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  cut1 = gtk_image_menu_item_new_with_mnemonic (_("Cu_t"));
  gtk_widget_set_name (cut1, "cut1");
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), cut1);
  gtk_widget_add_accelerator (cut1, "activate", accel_group,
                              GDK_X, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2048 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2048, "image2048");
  gtk_widget_show (image2048);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (cut1), image2048);

  copy1 = gtk_image_menu_item_new_with_mnemonic (_("_Copy"));
  gtk_widget_set_name (copy1, "copy1");
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), copy1);
  gtk_widget_add_accelerator (copy1, "activate", accel_group,
                              GDK_C, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image2049 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2049, "image2049");
  gtk_widget_show (image2049);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (copy1), image2049);

  paste1 = gtk_menu_item_new_with_mnemonic (_("_Paste"));
  gtk_widget_set_name (paste1, "paste1");
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), paste1);
  gtk_widget_add_accelerator (paste1, "activate", accel_group,
                              GDK_V, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  delete1 = gtk_image_menu_item_new_with_mnemonic (_("_Delete"));
  gtk_widget_set_name (delete1, "delete1");
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), delete1);
  gtk_widget_add_accelerator (delete1, "activate", accel_group,
                              GDK_Delete, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2050 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2050, "image2050");
  gtk_widget_show (image2050);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (delete1), image2050);

  separator5 = gtk_menu_item_new ();
  gtk_widget_set_name (separator5, "separator5");
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  set_marker_a1 = gtk_menu_item_new_with_mnemonic (_("Set Marker _A"));
  gtk_widget_set_name (set_marker_a1, "set_marker_a1");
  gtk_widget_show (set_marker_a1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), set_marker_a1);
  gtk_widget_add_accelerator (set_marker_a1, "activate", accel_group,
                              GDK_bracketleft, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  set_marker_b1 = gtk_menu_item_new_with_mnemonic (_("Set Marker _B"));
  gtk_widget_set_name (set_marker_b1, "set_marker_b1");
  gtk_widget_show (set_marker_b1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), set_marker_b1);
  gtk_widget_add_accelerator (set_marker_b1, "activate", accel_group,
                              GDK_bracketright, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  separator4 = gtk_menu_item_new ();
  gtk_widget_set_name (separator4, "separator4");
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  go_to_marker_a1 = gtk_menu_item_new_with_mnemonic (_("_Go to Marker A"));
  gtk_widget_set_name (go_to_marker_a1, "go_to_marker_a1");
  gtk_widget_show (go_to_marker_a1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), go_to_marker_a1);
  gtk_widget_add_accelerator (go_to_marker_a1, "activate", accel_group,
                              GDK_bracketleft, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  go_to_marker_b1 = gtk_menu_item_new_with_mnemonic (_("G_o to Marker B"));
  gtk_widget_set_name (go_to_marker_b1, "go_to_marker_b1");
  gtk_widget_show (go_to_marker_b1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), go_to_marker_b1);
  gtk_widget_add_accelerator (go_to_marker_b1, "activate", accel_group,
                              GDK_bracketright, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator10 = gtk_menu_item_new ();
  gtk_widget_set_name (separator10, "separator10");
  gtk_widget_show (separator10);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), separator10);
  gtk_widget_set_sensitive (separator10, FALSE);

  reset_edits1 = gtk_image_menu_item_new_with_mnemonic (_("_Reset Edits"));
  gtk_widget_set_name (reset_edits1, "reset_edits1");
  gtk_widget_show (reset_edits1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), reset_edits1);

  image2051 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image2051, "image2051");
  gtk_widget_show (image2051);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (reset_edits1), image2051);

  audio_source1 = gtk_menu_item_new_with_mnemonic (_("_Audio"));
  gtk_widget_set_name (audio_source1, "audio_source1");
  gtk_widget_show (audio_source1);
  gtk_container_add (GTK_CONTAINER (menuBar), audio_source1);

  audio_source1_menu = gtk_menu_new ();
  gtk_widget_set_name (audio_source1_menu, "audio_source1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (audio_source1), audio_source1_menu);

  source1 = gtk_menu_item_new_with_mnemonic (_("_Source"));
  gtk_widget_set_name (source1, "source1");
  gtk_widget_show (source1);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), source1);

  source1_menu = gtk_menu_new ();
  gtk_widget_set_name (source1_menu, "source1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (source1), source1_menu);

  current_video1 = gtk_menu_item_new_with_mnemonic (_("_Current Video"));
  gtk_widget_set_name (current_video1, "current_video1");
  gtk_widget_show (current_video1);
  gtk_container_add (GTK_CONTAINER (source1_menu), current_video1);
  gtk_widget_add_accelerator (current_video1, "activate", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  external_mpeg = gtk_menu_item_new_with_mnemonic (_("External _MPEG (MP2/MP3)..."));
  gtk_widget_set_name (external_mpeg, "external_mpeg");
  gtk_widget_show (external_mpeg);
  gtk_container_add (GTK_CONTAINER (source1_menu), external_mpeg);
  gtk_widget_add_accelerator (external_mpeg, "activate", accel_group,
                              GDK_E, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  external_wav1 = gtk_menu_item_new_with_mnemonic (_("External _WAV..."));
  gtk_widget_set_name (external_wav1, "external_wav1");
  gtk_widget_show (external_wav1);
  gtk_container_add (GTK_CONTAINER (source1_menu), external_wav1);
  gtk_widget_add_accelerator (external_wav1, "activate", accel_group,
                              GDK_W, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  external_ac1 = gtk_menu_item_new_with_mnemonic (_("External _AC3..."));
  gtk_widget_set_name (external_ac1, "external_ac1");
  gtk_widget_show (external_ac1);
  gtk_container_add (GTK_CONTAINER (source1_menu), external_ac1);
  gtk_widget_add_accelerator (external_ac1, "activate", accel_group,
                              GDK_3, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  none1 = gtk_menu_item_new_with_mnemonic (_("_None"));
  gtk_widget_set_name (none1, "none1");
  gtk_widget_show (none1);
  gtk_container_add (GTK_CONTAINER (source1_menu), none1);
  gtk_widget_add_accelerator (none1, "activate", accel_group,
                              GDK_N, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator12 = gtk_menu_item_new ();
  gtk_widget_set_name (separator12, "separator12");
  gtk_widget_show (separator12);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), separator12);
  gtk_widget_set_sensitive (separator12, FALSE);

  build_vbr_time_map1 = gtk_menu_item_new_with_mnemonic (_("_Build VBR Time Map"));
  gtk_widget_set_name (build_vbr_time_map1, "build_vbr_time_map1");
  gtk_widget_show (build_vbr_time_map1);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), build_vbr_time_map1);

  second_audio_track1 = gtk_menu_item_new_with_mnemonic (_("Second Audio _Track"));
  gtk_widget_set_name (second_audio_track1, "second_audio_track1");
  gtk_widget_show (second_audio_track1);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), second_audio_track1);

  second_audio_track1_menu = gtk_menu_new ();
  gtk_widget_set_name (second_audio_track1_menu, "second_audio_track1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (second_audio_track1), second_audio_track1_menu);

  mp3_file1 = gtk_menu_item_new_with_mnemonic (_("_MP3 File..."));
  gtk_widget_set_name (mp3_file1, "mp3_file1");
  gtk_widget_show (mp3_file1);
  gtk_container_add (GTK_CONTAINER (second_audio_track1_menu), mp3_file1);

  ac3_file1 = gtk_menu_item_new_with_mnemonic (_("_AC3 File..."));
  gtk_widget_set_name (ac3_file1, "ac3_file1");
  gtk_widget_show (ac3_file1);
  gtk_container_add (GTK_CONTAINER (second_audio_track1_menu), ac3_file1);

  pipe_audio_to1 = gtk_menu_item_new_with_mnemonic (_("_Pipe Audio to"));
  gtk_widget_set_name (pipe_audio_to1, "pipe_audio_to1");
  gtk_widget_show (pipe_audio_to1);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), pipe_audio_to1);

  pipe_audio_to1_menu = gtk_menu_new ();
  gtk_widget_set_name (pipe_audio_to1_menu, "pipe_audio_to1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (pipe_audio_to1), pipe_audio_to1_menu);

  to_toolame1 = gtk_menu_item_new_with_mnemonic (_("_tooLAME..."));
  gtk_widget_set_name (to_toolame1, "to_toolame1");
  gtk_widget_show (to_toolame1);
  gtk_container_add (GTK_CONTAINER (pipe_audio_to1_menu), to_toolame1);

  to_lame1 = gtk_menu_item_new_with_mnemonic (_("_LAME..."));
  gtk_widget_set_name (to_lame1, "to_lame1");
  gtk_widget_show (to_lame1);
  gtk_container_add (GTK_CONTAINER (pipe_audio_to1_menu), to_lame1);

  to_other1 = gtk_menu_item_new_with_mnemonic (_("_Other..."));
  gtk_widget_set_name (to_other1, "to_other1");
  gtk_widget_show (to_other1);
  gtk_container_add (GTK_CONTAINER (pipe_audio_to1_menu), to_other1);

  save_audio1 = gtk_menu_item_new_with_mnemonic (_("Sa_ve Audio..."));
  gtk_widget_set_name (save_audio1, "save_audio1");
  gtk_widget_show (save_audio1);
  gtk_container_add (GTK_CONTAINER (audio_source1_menu), save_audio1);
  gtk_widget_add_accelerator (save_audio1, "activate", accel_group,
                              GDK_B, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  misc1 = gtk_menu_item_new_with_mnemonic (_("_Misc"));
  gtk_widget_set_name (misc1, "misc1");
  gtk_widget_show (misc1);
  gtk_container_add (GTK_CONTAINER (menuBar), misc1);

  misc1_menu = gtk_menu_new ();
  gtk_widget_set_name (misc1_menu, "misc1_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (misc1), misc1_menu);

  preferences1 = gtk_menu_item_new_with_mnemonic (_("_Preferences"));
  gtk_widget_set_name (preferences1, "preferences1");
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), preferences1);
  gtk_widget_add_accelerator (preferences1, "activate", accel_group,
                              GDK_R, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator13 = gtk_menu_item_new ();
  gtk_widget_set_name (separator13, "separator13");
  gtk_widget_show (separator13);
  gtk_container_add (GTK_CONTAINER (misc1_menu), separator13);
  gtk_widget_set_sensitive (separator13, FALSE);

  check_frames = gtk_menu_item_new_with_mnemonic (_("_Check Frames (slow)"));
  gtk_widget_set_name (check_frames, "check_frames");
  gtk_widget_show (check_frames);
  gtk_container_add (GTK_CONTAINER (misc1_menu), check_frames);

  bitrate_histogram1 = gtk_menu_item_new_with_mnemonic (_("_Bitrate Histogram"));
  gtk_widget_set_name (bitrate_histogram1, "bitrate_histogram1");
  gtk_widget_show (bitrate_histogram1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), bitrate_histogram1);

  rebuild_frames = gtk_menu_item_new_with_mnemonic (_("_Rebuild Frames (I & B)"));
  gtk_widget_set_name (rebuild_frames, "rebuild_frames");
  gtk_widget_show (rebuild_frames);
  gtk_container_add (GTK_CONTAINER (misc1_menu), rebuild_frames);

  separator14 = gtk_menu_item_new ();
  gtk_widget_set_name (separator14, "separator14");
  gtk_widget_show (separator14);
  gtk_container_add (GTK_CONTAINER (misc1_menu), separator14);
  gtk_widget_set_sensitive (separator14, FALSE);

  ocr_vobsub_2_srt = gtk_menu_item_new_with_mnemonic (_("OCR (vobsub 2 srt)"));
  gtk_widget_set_name (ocr_vobsub_2_srt, "ocr_vobsub_2_srt");
  gtk_widget_show (ocr_vobsub_2_srt);
  gtk_container_add (GTK_CONTAINER (misc1_menu), ocr_vobsub_2_srt);

  separator15 = gtk_menu_item_new ();
  gtk_widget_set_name (separator15, "separator15");
  gtk_widget_show (separator15);
  gtk_container_add (GTK_CONTAINER (misc1_menu), separator15);
  gtk_widget_set_sensitive (separator15, FALSE);

  change_fps = gtk_menu_item_new_with_mnemonic (_("Change _fps..."));
  gtk_widget_set_name (change_fps, "change_fps");
  gtk_widget_show (change_fps);
  gtk_container_add (GTK_CONTAINER (misc1_menu), change_fps);

  videoencoder = gtk_menu_item_new_with_mnemonic (_("_Video Encoder"));
  gtk_widget_set_name (videoencoder, "videoencoder");
  gtk_widget_show (videoencoder);
  gtk_container_add (GTK_CONTAINER (misc1_menu), videoencoder);
  gtk_widget_add_accelerator (videoencoder, "activate", accel_group,
                              GDK_F3, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  audio_encoder1 = gtk_menu_item_new_with_mnemonic (_("_Audio Encoder"));
  gtk_widget_set_name (audio_encoder1, "audio_encoder1");
  gtk_widget_show (audio_encoder1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), audio_encoder1);
  gtk_widget_add_accelerator (audio_encoder1, "activate", accel_group,
                              GDK_F4, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  about1 = gtk_menu_item_new_with_mnemonic (_("A_bout"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuBar), about1);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox2, "handlebox2");
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox2), GTK_SHADOW_NONE);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  buttonOpen = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (buttonOpen, "buttonOpen");
  gtk_widget_show (buttonOpen);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), buttonOpen, _("Open video"), NULL);
  GTK_WIDGET_UNSET_FLAGS (buttonOpen, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (buttonOpen, GTK_CAN_DEFAULT);

  buttonSaveAvi = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_set_name (buttonSaveAvi, "buttonSaveAvi");
  gtk_widget_show (buttonSaveAvi);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), buttonSaveAvi, _("Save video"), NULL);
  GTK_WIDGET_UNSET_FLAGS (buttonSaveAvi, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (buttonSaveAvi, GTK_CAN_DEFAULT);

  buttonRecent = gtk_button_new ();
  gtk_widget_set_name (buttonRecent, "buttonRecent");
  gtk_widget_show (buttonRecent);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), buttonRecent, _("Recent files"), NULL);
  GTK_WIDGET_UNSET_FLAGS (buttonRecent, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (buttonRecent, GTK_CAN_DEFAULT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonRecent), alignment10);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox13);

  image633 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image633, "image633");
  gtk_widget_show (image633);
  gtk_box_pack_start (GTK_BOX (hbox13), image633, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Recent"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox13), label14, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);

  buttonInfo = gtk_button_new ();
  gtk_widget_set_name (buttonInfo, "buttonInfo");
  gtk_widget_show (buttonInfo);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), buttonInfo, _("Audio/video file information"), NULL);
  GTK_WIDGET_UNSET_FLAGS (buttonInfo, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (buttonInfo, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment11, "alignment11");
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonInfo), alignment11);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox15);

  image634 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image634, "image634");
  gtk_widget_show (image634);
  gtk_box_pack_start (GTK_BOX (hbox15), image634, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Info"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox15), label15, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  togglebuttonPreview = gtk_toggle_button_new_with_mnemonic (_("Preview [F7]"));
  gtk_widget_set_name (togglebuttonPreview, "togglebuttonPreview");
  gtk_widget_show (togglebuttonPreview);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), togglebuttonPreview, _("Open a preview window"), NULL);
  gtk_widget_add_accelerator (togglebuttonPreview, "clicked", accel_group,
                              GDK_F7, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  toggleOutput = gtk_toggle_button_new_with_mnemonic (_("Output [F8]"));
  gtk_widget_set_name (toggleOutput, "toggleOutput");
  gtk_widget_show (toggleOutput);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), toggleOutput, _("Display output video (playback only)"), NULL);
  gtk_widget_add_accelerator (toggleOutput, "clicked", accel_group,
                              GDK_F8, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox14, TRUE, TRUE, 0);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (hbox14), handlebox1, FALSE, FALSE, 0);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox1), GTK_SHADOW_NONE);
  gtk_handle_box_set_handle_position (GTK_HANDLE_BOX (handlebox1), GTK_POS_TOP);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (handlebox1), vbox5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, FALSE, FALSE, 0);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox6), frame2, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame2), vbox7);

  optionVCodec = gtk_option_menu_new ();
  gtk_widget_set_name (optionVCodec, "optionVCodec");
  gtk_widget_show (optionVCodec);
  gtk_box_pack_start (GTK_BOX (vbox7), optionVCodec, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (optionVCodec, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (optionVCodec, GTK_CAN_DEFAULT);

  buttonConfV = gtk_button_new_with_mnemonic (_("Configure[F3]"));
  gtk_widget_set_name (buttonConfV, "buttonConfV");
  gtk_widget_show (buttonConfV);
  gtk_box_pack_start (GTK_BOX (vbox7), buttonConfV, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (buttonConfV, "clicked", accel_group,
                              GDK_F3, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  buttonBitrate = gtk_button_new_with_mnemonic (_("Bitrate Calc    "));
  gtk_widget_set_name (buttonBitrate, "buttonBitrate");
  gtk_widget_show (buttonBitrate);
  gtk_box_pack_start (GTK_BOX (vbox7), buttonBitrate, FALSE, FALSE, 0);

  buttonFilters = gtk_button_new_with_mnemonic (_("V Filter    [F1]"));
  gtk_widget_set_name (buttonFilters, "buttonFilters");
  gtk_widget_show (buttonFilters);
  gtk_box_pack_start (GTK_BOX (vbox7), buttonFilters, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, buttonFilters, _("Video filters"), NULL);
  gtk_widget_add_accelerator (buttonFilters, "clicked", accel_group,
                              GDK_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  togglebuttonVideo = gtk_toggle_button_new_with_mnemonic (_("V Process[F5]"));
  gtk_widget_set_name (togglebuttonVideo, "togglebuttonVideo");
  gtk_widget_show (togglebuttonVideo);
  gtk_box_pack_start (GTK_BOX (vbox7), togglebuttonVideo, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, togglebuttonVideo, _("Process video"), NULL);
  gtk_widget_add_accelerator (togglebuttonVideo, "clicked", accel_group,
                              GDK_F5, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  Video = gtk_label_new (_("<b>Video</b>"));
  gtk_widget_set_name (Video, "Video");
  gtk_widget_show (Video);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), Video);
  gtk_label_set_use_markup (GTK_LABEL (Video), TRUE);
  gtk_label_set_justify (GTK_LABEL (Video), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Video), 0.5, 0.49);
  gtk_misc_set_padding (GTK_MISC (Video), 0, 3);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox6), frame3, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame3), vbox8);

  optionACodec = gtk_option_menu_new ();
  gtk_widget_set_name (optionACodec, "optionACodec");
  gtk_widget_show (optionACodec);
  gtk_box_pack_start (GTK_BOX (vbox8), optionACodec, FALSE, FALSE, 0);

  buttonConfA = gtk_button_new_with_mnemonic (_("Configure[F4]"));
  gtk_widget_set_name (buttonConfA, "buttonConfA");
  gtk_widget_show (buttonConfA);
  gtk_box_pack_start (GTK_BOX (vbox8), buttonConfA, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (buttonConfA, "clicked", accel_group,
                              GDK_F4, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  buttonAudioFilter = gtk_button_new_with_mnemonic (_("A Filter    [F2]"));
  gtk_widget_set_name (buttonAudioFilter, "buttonAudioFilter");
  gtk_widget_show (buttonAudioFilter);
  gtk_box_pack_start (GTK_BOX (vbox8), buttonAudioFilter, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, buttonAudioFilter, _("Audio filters"), NULL);
  gtk_widget_add_accelerator (buttonAudioFilter, "clicked", accel_group,
                              GDK_F2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  togglebuttonAudio = gtk_toggle_button_new_with_mnemonic (_("A Process[F6]"));
  gtk_widget_set_name (togglebuttonAudio, "togglebuttonAudio");
  gtk_widget_show (togglebuttonAudio);
  gtk_box_pack_start (GTK_BOX (vbox8), togglebuttonAudio, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, togglebuttonAudio, _("Process audio"), NULL);
  gtk_widget_add_accelerator (togglebuttonAudio, "clicked", accel_group,
                              GDK_F2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (togglebuttonAudio, "clicked", accel_group,
                              GDK_F6, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  Audio = gtk_label_new (_("<b>Audio</b>"));
  gtk_widget_set_name (Audio, "Audio");
  gtk_widget_show (Audio);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), Audio);
  gtk_label_set_use_markup (GTK_LABEL (Audio), TRUE);
  gtk_label_set_justify (GTK_LABEL (Audio), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (Audio), 0, 3);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox6), frame4, TRUE, TRUE, 0);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_set_name (optionmenu1, "optionmenu1");
  gtk_widget_show (optionmenu1);
  gtk_container_add (GTK_CONTAINER (frame4), optionmenu1);

  menu1 = gtk_menu_new ();
  gtk_widget_set_name (menu1, "menu1");

  avi1 = gtk_menu_item_new_with_mnemonic (_("Avi"));
  gtk_widget_set_name (avi1, "avi1");
  gtk_widget_show (avi1);
  gtk_container_add (GTK_CONTAINER (menu1), avi1);

  ogm1 = gtk_menu_item_new_with_mnemonic (_("OGM"));
  gtk_widget_set_name (ogm1, "ogm1");
  gtk_widget_show (ogm1);
  gtk_container_add (GTK_CONTAINER (menu1), ogm1);

  mpeg_video_only1 = gtk_menu_item_new_with_mnemonic (_("Mpeg video"));
  gtk_widget_set_name (mpeg_video_only1, "mpeg_video_only1");
  gtk_widget_show (mpeg_video_only1);
  gtk_container_add (GTK_CONTAINER (menu1), mpeg_video_only1);

  mpeg_ps1 = gtk_menu_item_new_with_mnemonic (_("Mpeg A+V (PS)"));
  gtk_widget_set_name (mpeg_ps1, "mpeg_ps1");
  gtk_widget_show (mpeg_ps1);
  gtk_container_add (GTK_CONTAINER (menu1), mpeg_ps1);

  mpeg_ts1 = gtk_menu_item_new_with_mnemonic (_("Mpeg A+V (TS)"));
  gtk_widget_set_name (mpeg_ts1, "mpeg_ts1");
  gtk_widget_show (mpeg_ts1);
  gtk_container_add (GTK_CONTAINER (menu1), mpeg_ts1);

  avi_dual_audio1 = gtk_menu_item_new_with_mnemonic (_("Avi, 2 audio"));
  gtk_widget_set_name (avi_dual_audio1, "avi_dual_audio1");
  gtk_widget_show (avi_dual_audio1);
  gtk_container_add (GTK_CONTAINER (menu1), avi_dual_audio1);

  avi_unpacked_vop1 = gtk_menu_item_new_with_mnemonic (_("Avi, unp. vop"));
  gtk_widget_set_name (avi_unpacked_vop1, "avi_unpacked_vop1");
  gtk_widget_show (avi_unpacked_vop1);
  gtk_container_add (GTK_CONTAINER (menu1), avi_unpacked_vop1);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), menu1);

  label17 = gtk_label_new (_("<b>Outp. fmt</b>"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  guiDrawing = gtk_drawing_area_new ();
  gtk_widget_set_name (guiDrawing, "guiDrawing");
  gtk_widget_show (guiDrawing);
  gtk_box_pack_start (GTK_BOX (hbox14), guiDrawing, TRUE, TRUE, 0);
  gtk_widget_set_size_request (guiDrawing, 512, 288);
  gtk_widget_set_sensitive (guiDrawing, FALSE);

  sliderNavigate = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 99.99, 0.01, 1, 0)));
  gtk_widget_set_name (sliderNavigate, "sliderNavigate");
  gtk_widget_show (sliderNavigate);
  gtk_box_pack_start (GTK_BOX (vbox1), sliderNavigate, FALSE, FALSE, 0);
  gtk_widget_set_size_request (sliderNavigate, -1, 24);
  GTK_WIDGET_UNSET_FLAGS (sliderNavigate, GTK_CAN_FOCUS);
  gtk_scale_set_value_pos (GTK_SCALE (sliderNavigate), GTK_POS_LEFT);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox17, "hbox17");
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox17, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox17), vbox3, TRUE, TRUE, 0);

  handlebox3 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox3, "handlebox3");
  gtk_widget_show (handlebox3);
  gtk_box_pack_start (GTK_BOX (vbox3), handlebox3, TRUE, FALSE, 0);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox3), GTK_SHADOW_NONE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (handlebox3), hbox10);
  gtk_widget_set_size_request (hbox10, -1, 24);

  buttonPlay = gtk_button_new ();
  gtk_widget_set_name (buttonPlay, "buttonPlay");
  gtk_widget_show (buttonPlay);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonPlay, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonPlay, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonPlay, _("Start/stop playback"), NULL);
  gtk_widget_add_accelerator (buttonPlay, "clicked", accel_group,
                              GDK_space, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image591 = create_pixmap (mainWindow, "play.xpm");
  gtk_widget_set_name (image591, "image591");
  gtk_widget_show (image591);
  gtk_container_add (GTK_CONTAINER (buttonPlay), image591);

  buttonStop = gtk_button_new ();
  gtk_widget_set_name (buttonStop, "buttonStop");
  gtk_widget_show (buttonStop);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonStop, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonStop, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonStop, _("Stop"), NULL);
  gtk_widget_add_accelerator (buttonStop, "clicked", accel_group,
                              GDK_P, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image592 = create_pixmap (mainWindow, "stop.xpm");
  gtk_widget_set_name (image592, "image592");
  gtk_widget_show (image592);
  gtk_container_add (GTK_CONTAINER (buttonStop), image592);

  buttonPrevFrame = gtk_button_new ();
  gtk_widget_set_name (buttonPrevFrame, "buttonPrevFrame");
  gtk_widget_show (buttonPrevFrame);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonPrevFrame, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonPrevFrame, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonPrevFrame, _("Previous frame [4]"), NULL);
  gtk_widget_add_accelerator (buttonPrevFrame, "clicked", accel_group,
                              GDK_KP_4, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image593 = create_pixmap (mainWindow, "backward.xpm");
  gtk_widget_set_name (image593, "image593");
  gtk_widget_show (image593);
  gtk_container_add (GTK_CONTAINER (buttonPrevFrame), image593);

  buttonNextFrame = gtk_button_new ();
  gtk_widget_set_name (buttonNextFrame, "buttonNextFrame");
  gtk_widget_show (buttonNextFrame);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonNextFrame, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonNextFrame, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonNextFrame, _("Next frame [6]"), NULL);
  gtk_widget_add_accelerator (buttonNextFrame, "clicked", accel_group,
                              GDK_KP_6, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image594 = create_pixmap (mainWindow, "forward.xpm");
  gtk_widget_set_name (image594, "image594");
  gtk_widget_show (image594);
  gtk_container_add (GTK_CONTAINER (buttonNextFrame), image594);

  buttonPrevKFrame = gtk_button_new ();
  gtk_widget_set_name (buttonPrevKFrame, "buttonPrevKFrame");
  gtk_widget_show (buttonPrevKFrame);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonPrevKFrame, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonPrevKFrame, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonPrevKFrame, _("Previous keyframe[2]"), NULL);
  gtk_widget_add_accelerator (buttonPrevKFrame, "clicked", accel_group,
                              GDK_KP_2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image595 = create_pixmap (mainWindow, "Kbackward.xpm");
  gtk_widget_set_name (image595, "image595");
  gtk_widget_show (image595);
  gtk_container_add (GTK_CONTAINER (buttonPrevKFrame), image595);

  buttonNextKFrame = gtk_button_new ();
  gtk_widget_set_name (buttonNextKFrame, "buttonNextKFrame");
  gtk_widget_show (buttonNextKFrame);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonNextKFrame, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonNextKFrame, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonNextKFrame, _("Next keyframe[8]"), NULL);
  gtk_widget_add_accelerator (buttonNextKFrame, "clicked", accel_group,
                              GDK_KP_8, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image596 = create_pixmap (mainWindow, "Kforward.xpm");
  gtk_widget_set_name (image596, "image596");
  gtk_widget_show (image596);
  gtk_container_add (GTK_CONTAINER (buttonNextKFrame), image596);

  buttonMarkA = gtk_button_new ();
  gtk_widget_set_name (buttonMarkA, "buttonMarkA");
  gtk_widget_show (buttonMarkA);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonMarkA, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonMarkA, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonMarkA, _("Selection: start"), NULL);

  image597 = create_pixmap (mainWindow, "markA.xpm");
  gtk_widget_set_name (image597, "image597");
  gtk_widget_show (image597);
  gtk_container_add (GTK_CONTAINER (buttonMarkA), image597);

  buttonMarkB = gtk_button_new ();
  gtk_widget_set_name (buttonMarkB, "buttonMarkB");
  gtk_widget_show (buttonMarkB);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonMarkB, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonMarkB, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonMarkB, _("Selection: end"), NULL);

  image598 = create_pixmap (mainWindow, "markB.xpm");
  gtk_widget_set_name (image598, "image598");
  gtk_widget_show (image598);
  gtk_container_add (GTK_CONTAINER (buttonMarkB), image598);

  buttonBegin = gtk_button_new ();
  gtk_widget_set_name (buttonBegin, "buttonBegin");
  gtk_widget_show (buttonBegin);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonBegin, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonBegin, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonBegin, _("First frame"), NULL);
  gtk_widget_add_accelerator (buttonBegin, "clicked", accel_group,
                              GDK_Home, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image599 = create_pixmap (mainWindow, "begin.xpm");
  gtk_widget_set_name (image599, "image599");
  gtk_widget_show (image599);
  gtk_container_add (GTK_CONTAINER (buttonBegin), image599);

  buttonEnd = gtk_button_new ();
  gtk_widget_set_name (buttonEnd, "buttonEnd");
  gtk_widget_show (buttonEnd);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonEnd, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonEnd, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonEnd, _("Last frame"), NULL);
  gtk_widget_add_accelerator (buttonEnd, "clicked", accel_group,
                              GDK_End, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image600 = create_pixmap (mainWindow, "end.xpm");
  gtk_widget_set_name (image600, "image600");
  gtk_widget_show (image600);
  gtk_container_add (GTK_CONTAINER (buttonEnd), image600);

  buttonPrevBlack = gtk_button_new ();
  gtk_widget_set_name (buttonPrevBlack, "buttonPrevBlack");
  gtk_widget_show (buttonPrevBlack);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonPrevBlack, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonPrevBlack, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonPrevBlack, _("Previous black frame"), NULL);

  image601 = create_pixmap (mainWindow, "xpm_prevblack.xpm");
  gtk_widget_set_name (image601, "image601");
  gtk_widget_show (image601);
  gtk_container_add (GTK_CONTAINER (buttonPrevBlack), image601);

  buttonNextBlack = gtk_button_new ();
  gtk_widget_set_name (buttonNextBlack, "buttonNextBlack");
  gtk_widget_show (buttonNextBlack);
  gtk_box_pack_start (GTK_BOX (hbox10), buttonNextBlack, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (buttonNextBlack, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonNextBlack, _("Next black frame"), NULL);

  image602 = create_pixmap (mainWindow, "xpm_nextblack.xpm");
  gtk_widget_set_name (image602, "image602");
  gtk_widget_show (image602);
  gtk_container_add (GTK_CONTAINER (buttonNextBlack), image602);

  hbox16 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox16, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox16), 3);

  label1 = gtk_label_new (_("Frame: "));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox16), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  boxCurFrame = gtk_entry_new ();
  gtk_widget_set_name (boxCurFrame, "boxCurFrame");
  gtk_widget_show (boxCurFrame);
  gtk_box_pack_start (GTK_BOX (hbox16), boxCurFrame, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, boxCurFrame, _("Current frame"), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (boxCurFrame), 8);
  gtk_entry_set_text (GTK_ENTRY (boxCurFrame), _("0"));
  gtk_entry_set_width_chars (GTK_ENTRY (boxCurFrame), 8);

  labelTotalFrame = gtk_label_new (_("/0000000"));
  gtk_widget_set_name (labelTotalFrame, "labelTotalFrame");
  gtk_widget_show (labelTotalFrame);
  gtk_box_pack_start (GTK_BOX (hbox16), labelTotalFrame, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (labelTotalFrame), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (labelTotalFrame), 5, 0);

  label4 = gtk_label_new (_("Time: "));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox16), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  boxCurTime = gtk_entry_new ();
  gtk_widget_set_name (boxCurTime, "boxCurTime");
  gtk_widget_show (boxCurTime);
  gtk_box_pack_start (GTK_BOX (hbox16), boxCurTime, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, boxCurTime, _("Current time"), NULL);
  gtk_entry_set_text (GTK_ENTRY (boxCurTime), _("00:00:00.000"));
  gtk_entry_set_width_chars (GTK_ENTRY (boxCurTime), 13);

  labelTotalTime = gtk_label_new (_("/00:00:00,000"));
  gtk_widget_set_name (labelTotalTime, "labelTotalTime");
  gtk_widget_show (labelTotalTime);
  gtk_box_pack_start (GTK_BOX (hbox16), labelTotalTime, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (labelTotalTime), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (labelTotalTime), 5, 0);

  labelFrameType = gtk_label_new (_("Frame: ?"));
  gtk_widget_set_name (labelFrameType, "labelFrameType");
  gtk_widget_show (labelFrameType);
  gtk_box_pack_start (GTK_BOX (hbox16), labelFrameType, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (labelFrameType), GTK_JUSTIFY_LEFT);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox17), frame1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 3);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame1), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 3);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox4), table1, TRUE, TRUE, 0);

  labelMarkA = gtk_label_new (_(" 0000000"));
  gtk_widget_set_name (labelMarkA, "labelMarkA");
  gtk_widget_show (labelMarkA);
  gtk_table_attach (GTK_TABLE (table1), labelMarkA, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (labelMarkA), GTK_JUSTIFY_LEFT);

  labelMarkB = gtk_label_new (_(" 0000000"));
  gtk_widget_set_name (labelMarkB, "labelMarkB");
  gtk_widget_show (labelMarkB);
  gtk_table_attach (GTK_TABLE (table1), labelMarkB, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (labelMarkB), GTK_JUSTIFY_LEFT);

  buttonGotoA = gtk_button_new_with_mnemonic (_("A:"));
  gtk_widget_set_name (buttonGotoA, "buttonGotoA");
  gtk_widget_show (buttonGotoA);
  gtk_table_attach (GTK_TABLE (table1), buttonGotoA, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (buttonGotoA, -1, 20);
  GTK_WIDGET_UNSET_FLAGS (buttonGotoA, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonGotoA, _("Go to marker A"), NULL);

  buttonGotoB = gtk_button_new_with_mnemonic (_("B:"));
  gtk_widget_set_name (buttonGotoB, "buttonGotoB");
  gtk_widget_show (buttonGotoB);
  gtk_table_attach (GTK_TABLE (table1), buttonGotoB, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_size_request (buttonGotoB, -1, 20);
  GTK_WIDGET_UNSET_FLAGS (buttonGotoB, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, buttonGotoB, _("Go to marker B"), NULL);

  label16 = gtk_label_new (_("Selection"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label16);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, menuBar, "menuBar");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, open_video1, "open_video1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2035, "image2035");
  GLADE_HOOKUP_OBJECT (mainWindow, run_script1, "run_script1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2036, "image2036");
  GLADE_HOOKUP_OBJECT (mainWindow, append_video1, "append_video1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2037, "image2037");
  GLADE_HOOKUP_OBJECT (mainWindow, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_stuff, "save_stuff");
  GLADE_HOOKUP_OBJECT (mainWindow, save_stuff_menu, "save_stuff_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, save_as_avi1, "save_as_avi1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_images1, "save_images1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_images1_menu, "save_images1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, save_image1, "save_image1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_jpg_image1, "save_jpg_image1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_selection_as_jpegs1, "save_selection_as_jpegs1");
  GLADE_HOOKUP_OBJECT (mainWindow, requantize_mpeg1, "requantize_mpeg1");
  GLADE_HOOKUP_OBJECT (mainWindow, project1, "project1");
  GLADE_HOOKUP_OBJECT (mainWindow, project1_menu, "project1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, load_project, "load_project");
  GLADE_HOOKUP_OBJECT (mainWindow, image2038, "image2038");
  GLADE_HOOKUP_OBJECT (mainWindow, save_project_as1, "save_project_as1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2039, "image2039");
  GLADE_HOOKUP_OBJECT (mainWindow, save_current_project, "save_current_project");
  GLADE_HOOKUP_OBJECT (mainWindow, image2040, "image2040");
  GLADE_HOOKUP_OBJECT (mainWindow, avi_muxer_options1, "avi_muxer_options1");
  GLADE_HOOKUP_OBJECT (mainWindow, video_informations1, "video_informations1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2041, "image2041");
  GLADE_HOOKUP_OBJECT (mainWindow, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2042, "image2042");
  GLADE_HOOKUP_OBJECT (mainWindow, play_1, "play_1");
  GLADE_HOOKUP_OBJECT (mainWindow, play_1_menu, "play_1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, play_video1, "play_video1");
  GLADE_HOOKUP_OBJECT (mainWindow, decoder_options1, "decoder_options1");
  GLADE_HOOKUP_OBJECT (mainWindow, set_postprocessing1, "set_postprocessing1");
  GLADE_HOOKUP_OBJECT (mainWindow, separator9, "separator9");
  GLADE_HOOKUP_OBJECT (mainWindow, next_frame1, "next_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2043, "image2043");
  GLADE_HOOKUP_OBJECT (mainWindow, previous_frame1, "previous_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2044, "image2044");
  GLADE_HOOKUP_OBJECT (mainWindow, next_intra_frame1, "next_intra_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2045, "image2045");
  GLADE_HOOKUP_OBJECT (mainWindow, previous_intra_frame1, "previous_intra_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2046, "image2046");
  GLADE_HOOKUP_OBJECT (mainWindow, search_next_black_frame1, "search_next_black_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, search_previous_black_frame1, "search_previous_black_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, jum_to_frame1, "jum_to_frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2047, "image2047");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2048, "image2048");
  GLADE_HOOKUP_OBJECT (mainWindow, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2049, "image2049");
  GLADE_HOOKUP_OBJECT (mainWindow, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (mainWindow, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2050, "image2050");
  GLADE_HOOKUP_OBJECT (mainWindow, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (mainWindow, set_marker_a1, "set_marker_a1");
  GLADE_HOOKUP_OBJECT (mainWindow, set_marker_b1, "set_marker_b1");
  GLADE_HOOKUP_OBJECT (mainWindow, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (mainWindow, go_to_marker_a1, "go_to_marker_a1");
  GLADE_HOOKUP_OBJECT (mainWindow, go_to_marker_b1, "go_to_marker_b1");
  GLADE_HOOKUP_OBJECT (mainWindow, separator10, "separator10");
  GLADE_HOOKUP_OBJECT (mainWindow, reset_edits1, "reset_edits1");
  GLADE_HOOKUP_OBJECT (mainWindow, image2051, "image2051");
  GLADE_HOOKUP_OBJECT (mainWindow, audio_source1, "audio_source1");
  GLADE_HOOKUP_OBJECT (mainWindow, audio_source1_menu, "audio_source1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, source1, "source1");
  GLADE_HOOKUP_OBJECT (mainWindow, source1_menu, "source1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, current_video1, "current_video1");
  GLADE_HOOKUP_OBJECT (mainWindow, external_mpeg, "external_mpeg");
  GLADE_HOOKUP_OBJECT (mainWindow, external_wav1, "external_wav1");
  GLADE_HOOKUP_OBJECT (mainWindow, external_ac1, "external_ac1");
  GLADE_HOOKUP_OBJECT (mainWindow, none1, "none1");
  GLADE_HOOKUP_OBJECT (mainWindow, separator12, "separator12");
  GLADE_HOOKUP_OBJECT (mainWindow, build_vbr_time_map1, "build_vbr_time_map1");
  GLADE_HOOKUP_OBJECT (mainWindow, second_audio_track1, "second_audio_track1");
  GLADE_HOOKUP_OBJECT (mainWindow, second_audio_track1_menu, "second_audio_track1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, mp3_file1, "mp3_file1");
  GLADE_HOOKUP_OBJECT (mainWindow, ac3_file1, "ac3_file1");
  GLADE_HOOKUP_OBJECT (mainWindow, pipe_audio_to1, "pipe_audio_to1");
  GLADE_HOOKUP_OBJECT (mainWindow, pipe_audio_to1_menu, "pipe_audio_to1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, to_toolame1, "to_toolame1");
  GLADE_HOOKUP_OBJECT (mainWindow, to_lame1, "to_lame1");
  GLADE_HOOKUP_OBJECT (mainWindow, to_other1, "to_other1");
  GLADE_HOOKUP_OBJECT (mainWindow, save_audio1, "save_audio1");
  GLADE_HOOKUP_OBJECT (mainWindow, misc1, "misc1");
  GLADE_HOOKUP_OBJECT (mainWindow, misc1_menu, "misc1_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, preferences1, "preferences1");
  GLADE_HOOKUP_OBJECT (mainWindow, separator13, "separator13");
  GLADE_HOOKUP_OBJECT (mainWindow, check_frames, "check_frames");
  GLADE_HOOKUP_OBJECT (mainWindow, bitrate_histogram1, "bitrate_histogram1");
  GLADE_HOOKUP_OBJECT (mainWindow, rebuild_frames, "rebuild_frames");
  GLADE_HOOKUP_OBJECT (mainWindow, separator14, "separator14");
  GLADE_HOOKUP_OBJECT (mainWindow, ocr_vobsub_2_srt, "ocr_vobsub_2_srt");
  GLADE_HOOKUP_OBJECT (mainWindow, separator15, "separator15");
  GLADE_HOOKUP_OBJECT (mainWindow, change_fps, "change_fps");
  GLADE_HOOKUP_OBJECT (mainWindow, videoencoder, "videoencoder");
  GLADE_HOOKUP_OBJECT (mainWindow, audio_encoder1, "audio_encoder1");
  GLADE_HOOKUP_OBJECT (mainWindow, about1, "about1");
  GLADE_HOOKUP_OBJECT (mainWindow, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (mainWindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonOpen, "buttonOpen");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonSaveAvi, "buttonSaveAvi");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonRecent, "buttonRecent");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (mainWindow, image633, "image633");
  GLADE_HOOKUP_OBJECT (mainWindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonInfo, "buttonInfo");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (mainWindow, image634, "image634");
  GLADE_HOOKUP_OBJECT (mainWindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (mainWindow, togglebuttonPreview, "togglebuttonPreview");
  GLADE_HOOKUP_OBJECT (mainWindow, toggleOutput, "toggleOutput");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (mainWindow, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (mainWindow, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (mainWindow, optionVCodec, "optionVCodec");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonConfV, "buttonConfV");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonBitrate, "buttonBitrate");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonFilters, "buttonFilters");
  GLADE_HOOKUP_OBJECT (mainWindow, togglebuttonVideo, "togglebuttonVideo");
  GLADE_HOOKUP_OBJECT (mainWindow, Video, "Video");
  GLADE_HOOKUP_OBJECT (mainWindow, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (mainWindow, optionACodec, "optionACodec");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonConfA, "buttonConfA");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonAudioFilter, "buttonAudioFilter");
  GLADE_HOOKUP_OBJECT (mainWindow, togglebuttonAudio, "togglebuttonAudio");
  GLADE_HOOKUP_OBJECT (mainWindow, Audio, "Audio");
  GLADE_HOOKUP_OBJECT (mainWindow, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (mainWindow, optionmenu1, "optionmenu1");
  GLADE_HOOKUP_OBJECT (mainWindow, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (mainWindow, avi1, "avi1");
  GLADE_HOOKUP_OBJECT (mainWindow, ogm1, "ogm1");
  GLADE_HOOKUP_OBJECT (mainWindow, mpeg_video_only1, "mpeg_video_only1");
  GLADE_HOOKUP_OBJECT (mainWindow, mpeg_ps1, "mpeg_ps1");
  GLADE_HOOKUP_OBJECT (mainWindow, mpeg_ts1, "mpeg_ts1");
  GLADE_HOOKUP_OBJECT (mainWindow, avi_dual_audio1, "avi_dual_audio1");
  GLADE_HOOKUP_OBJECT (mainWindow, avi_unpacked_vop1, "avi_unpacked_vop1");
  GLADE_HOOKUP_OBJECT (mainWindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (mainWindow, guiDrawing, "guiDrawing");
  GLADE_HOOKUP_OBJECT (mainWindow, sliderNavigate, "sliderNavigate");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, handlebox3, "handlebox3");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonPlay, "buttonPlay");
  GLADE_HOOKUP_OBJECT (mainWindow, image591, "image591");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonStop, "buttonStop");
  GLADE_HOOKUP_OBJECT (mainWindow, image592, "image592");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonPrevFrame, "buttonPrevFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, image593, "image593");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonNextFrame, "buttonNextFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, image594, "image594");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonPrevKFrame, "buttonPrevKFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, image595, "image595");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonNextKFrame, "buttonNextKFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, image596, "image596");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonMarkA, "buttonMarkA");
  GLADE_HOOKUP_OBJECT (mainWindow, image597, "image597");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonMarkB, "buttonMarkB");
  GLADE_HOOKUP_OBJECT (mainWindow, image598, "image598");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonBegin, "buttonBegin");
  GLADE_HOOKUP_OBJECT (mainWindow, image599, "image599");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonEnd, "buttonEnd");
  GLADE_HOOKUP_OBJECT (mainWindow, image600, "image600");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonPrevBlack, "buttonPrevBlack");
  GLADE_HOOKUP_OBJECT (mainWindow, image601, "image601");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonNextBlack, "buttonNextBlack");
  GLADE_HOOKUP_OBJECT (mainWindow, image602, "image602");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (mainWindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (mainWindow, boxCurFrame, "boxCurFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, labelTotalFrame, "labelTotalFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainWindow, boxCurTime, "boxCurTime");
  GLADE_HOOKUP_OBJECT (mainWindow, labelTotalTime, "labelTotalTime");
  GLADE_HOOKUP_OBJECT (mainWindow, labelFrameType, "labelFrameType");
  GLADE_HOOKUP_OBJECT (mainWindow, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (mainWindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (mainWindow, labelMarkA, "labelMarkA");
  GLADE_HOOKUP_OBJECT (mainWindow, labelMarkB, "labelMarkB");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonGotoA, "buttonGotoA");
  GLADE_HOOKUP_OBJECT (mainWindow, buttonGotoB, "buttonGotoB");
  GLADE_HOOKUP_OBJECT (mainWindow, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (mainWindow), accel_group);

  return mainWindow;
}

